var marks = 100;
var name = "Abdullah";
var age;
var company = null;
var salary = undefined;
var isStudent = false;
console.log("Marks = ", marks);
console.log("Name = ", name);
console.log("Age = ", age);
console.log("Company = ", company);
console.log("Salary = ", salary);
console.log("Is A Student = ", isStudent);